### ISSUE TITLE
Improve readability and compatibility

### ISSUE THREAD

**Issue by g4brielvs** [ramarty/blackmarblepy#11]
This is a fantastic project, @ramarty! 

With the success of [blackmarbler](https://github.com/ramarty/blackmarbler) I started an equivalent Python package (pyblackmarble). However, as we chatted, it would be beneficial to join efforts instead and maintain [blackmarblepy](https://github.com/ramarty/blackmarblepy) solely. At some point, the repository could be transferred to the [World Bank](https://github.com/worldbank). If you are open to it, I am creating this issue to track contributions to improve [blackmarblepy](https://github.com/ramarty/blackmarblepy) in regard to readability, compatibility and making it more pythonic. I'll open separate pull requests.  

## Tasks 

- [x] #13

**Comment by ramarty** [comment]
@g4brielvs Amazing, thanks so much! Yep, def makes sense to join efforts on this. I use more R than Python, so definitely appreciate you helping to make this more pythonic too.

**Comment by g4brielvs** [comment]
Closing in lieu of https://github.com/worldbank/blackmarblepy/issues/4.
