### ISSUE TITLE
Conform to PEP 517 and PEP 621

### ISSUE THREAD

**Issue by g4brielvs** [ramarty/blackmarblepy#13]
It is recommended to adopt [PEP 517](https://peps.python.org/pep-0517/) and [PEP 621](https://peps.python.org/pep-0621/). If amenable, I'd open a PR for this.

**Comment by ramarty** [comment]
@g4brielvs oh perfect - sounds good to me!

**Comment by g4brielvs** [comment]
Closing in lieu of https://github.com/worldbank/blackmarblepy/issues/5.
